# Generated by Django 3.0.2 on 2020-03-11 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0002_question_question_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyinstance',
            name='loggist',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='monthly_income',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='occupation',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='secondary_monthly_income',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='secondary_occupation',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
