# Generated by Django 3.0.2 on 2020-03-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_village'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maritalstatus',
            name='status',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='relationtohead',
            name='relation',
            field=models.CharField(max_length=30),
        ),
    ]
