# Generated by Django 3.0.2 on 2020-03-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20200312_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='householdmember',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='occupation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='maritalstatus',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='relationtohead',
            name='relation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='village',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
